"""
Resume Download Cloud Function
────────────────────────────────
Entry point : get_resume
Runtime     : Python 3.12
Region      : asia-south1

Flow:
  1. Receive candidate_id (query param or JSON body)
  2. Query BigQuery candidates table for gcs_pdf_path AND job_id
  3. Resolve the correct GCS blob path (handles legacy bad paths)
  4. Download PDF bytes from GCS
  5. Stream back as application/pdf

Permissions needed on Cloud Function service account:
  - BigQuery Data Viewer  (query candidates table)
  - Storage Object Viewer (read PDF from GCS bucket)
"""

import io
import json
import functions_framework
from google.cloud import bigquery, storage
from pypdf import PdfReader
import vertexai
from vertexai.generative_models import GenerativeModel

# ── CONFIG ────────────────────────────────────────────────────────────────────

PROJECT_ID  = "atgeir-moae-dev"
DATASET_ID  = "hr_dataset"
TABLE_ID    = "candidates"
BUCKET_NAME = "hr-data-source-at"
REGION      = "global"

# Initialize Vertex AI globally for warm container reuse
vertexai.init(project=PROJECT_ID, location=REGION)
ai_model = GenerativeModel("gemini-3.5-flash")

# ── CLIENTS ───────────────────────────────────────────────────────────────────

bq_client  = bigquery.Client(project=PROJECT_ID)
gcs_client = storage.Client(project=PROJECT_ID)

# ── CORS ──────────────────────────────────────────────────────────────────────

CORS_HEADERS = {
    "Access-Control-Allow-Origin"  : "*",
    "Access-Control-Allow-Methods" : "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers" : "Content-Type, Authorization",
    # CRITICAL: Without this line, the UI's fetch() cannot see our custom header
    "Access-Control-Expose-Headers": "X-AI-Generated-Percentage", 
    "Access-Control-Max-Age"       : "3600",
}


def _cors_preflight():
    return ("", 204, CORS_HEADERS)


def _error(message: str, status: int = 400):
    headers = {**CORS_HEADERS, "Content-Type": "application/json"}
    return (json.dumps({"success": False, "error": message}), status, headers)


# ── Fetch gcs_pdf_path + job_id from BigQuery ────────────────────────────────

def fetch_candidate_info(candidate_id: str) -> dict | None:
    query = f"""
        SELECT gcs_pdf_path, job_id
        FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
        WHERE candidate_id = @candidate_id
        LIMIT 1
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("candidate_id", "STRING", candidate_id)
        ]
    )
    rows = list(bq_client.query(query, job_config=job_config).result())
    if not rows or not rows[0].gcs_pdf_path:
        return None
    return {
        "gcs_pdf_path": rows[0].gcs_pdf_path,
        "job_id"      : rows[0].job_id if rows[0].job_id else None,
    }


# ── Resolve the correct blob name ────────────────────────────────────────────

def resolve_blob_name(gcs_pdf_path: str, job_id: str | None) -> str:
    path = gcs_pdf_path
    if path.startswith("gs://"):
        path = path[len("gs://"):]
        path = "/".join(path.split("/")[1:])

    filename = path.split("/")[-1]

    if job_id:
        return f"resumes/{job_id}/{filename}"

    return path


# ── Download PDF bytes from GCS ───────────────────────────────────────────────

def download_pdf(blob_name: str) -> bytes:
    bucket = gcs_client.bucket(BUCKET_NAME)
    blob   = bucket.blob(blob_name)
    return blob.download_as_bytes()


# ── AI Forensic Analysis ──────────────────────────────────────────────────────

def assess_ai_percentage(pdf_bytes: bytes) -> str:
    """Extracts PDF text and asks Gemini Flash to assess LLM probability."""
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        text = "\n".join([page.extract_text() for page in reader.pages if page.extract_text()])
        
        if not text.strip():
            return "0"

        prompt = f"""
        You are an expert forensic copywriter. Analyze this resume text. 
        Calculate the percentage probability (0 to 100) that this text was generated by an AI. Look for telltale signs: extreme semantic symmetry, robotic transition words ('spearheaded', 'testament to', 'fostered'), zero personal idiosyncrasies, and hyper-dense buzzword packing.
        
        Return strictly a JSON object matching this schema: {{"ai_percentage": integer}}
        
        Resume Text:
        '''{text[:10000]}'''
        """

        response = ai_model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"}
        )
        
        result = json.loads(response.text)
        return str(result.get("ai_percentage", 0))

    except Exception as e:
        print(f"AI Assessment failed: {str(e)}")
        return "unknown"


# ── Entry point ───────────────────────────────────────────────────────────────

@functions_framework.http
def get_resume(request):
    if request.method == "OPTIONS":
        return _cors_preflight()

    candidate_id = request.args.get("candidate_id", "").strip()

    if not candidate_id and request.method == "POST":
        try:
            body         = request.get_json(silent=True) or {}
            candidate_id = body.get("candidate_id", "").strip()
        except Exception:
            pass

    if not candidate_id:
        return _error("'candidate_id' is required", 400)

    try:
        info = fetch_candidate_info(candidate_id)
    except Exception as e:
        return _error(f"BigQuery error: {str(e)}", 500)

    if not info:
        return _error(f"No resume found for candidate_id: {candidate_id}", 404)

    blob_name = resolve_blob_name(info["gcs_pdf_path"], info.get("job_id"))
    filename  = blob_name.split("/")[-1] or "resume.pdf"

    try:
        pdf_bytes = download_pdf(blob_name)
    except Exception as e:
        return _error(f"Failed to fetch resume from GCS. Path: {blob_name!r}", 500)

    # 1. Run the AI check on the bytes we just pulled
    ai_score = assess_ai_percentage(pdf_bytes)

    # 2. Slip it into the headers
    headers = {
        **CORS_HEADERS,
        "Content-Type"             : "application/pdf",
        "Content-Disposition"      : f'inline; filename="{filename}"',
        "Content-Length"           : str(len(pdf_bytes)),
        "X-AI-Generated-Percentage": ai_score,
    }

    return (pdf_bytes, 200, headers)