steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_API_BASE_URL=http://backend-service:8080'
      - '--build-arg=VITE_LIST_JOBS_URL=http://backend-service:8080/api/job-listing'
      - '--build-arg=VITE_RESUME_URL=http://backend-service:8080/api/resume-downloader'
      - '--build-arg=VITE_SEND_EMAIL_URL=http://backend-service:8080/api/send-email'
      - '--build-arg=VITE_SAVE_SLOTS_URL=http://backend-service:8080/api/save-candidate-slots'
      - '--build-arg=VITE_SAVE_INTERVIEWER_URL=http://backend-service:8080/api/save-interviewer'
      - '--build-arg=VITE_DATA_MANAGER_URL=http://backend-service:8080/api/data-manager'
      - '--build-arg=VITE_RUN_PIPELINE_URL=http://backend-service:8080/api/agentic-flow'
      - '--build-arg=VITE_APP_ENV=production'
      - '--build-arg=VITE_UPDATE_CANDIDATE_STATUS_URL=http://backend-service:8080/api/update-candidate-status'
      - '--build-arg=VITE_GENERATE_QUESTIONS_URL=http://backend-service:8080/api/generate-interview-questions'
      - '--build-arg=VITE_OFFER_AGENT_URL=http://backend-service:8080/api/offer-agent'
      - '--build-arg=VITE_UPLOAD_RESUME_URL=http://backend-service:8080/api/resume-uploader'
      - '--build-arg=VITE_REFER_CANDIDATE_URL=http://backend-service:8080/api/refer-candidate'
      - '--build-arg=VITE_GET_CANDIDATE_SLOTS_URL=http://backend-service:8080/api/get-candidate-slots'
      - '--build-arg=VITE_CHAT_AGENT_URL=http://backend-service:8080/api/chat-agent'
      - '--build-arg=VITE_CHECK_LOGIN_URL=http://backend-service:8080/api/check-login'
      - '-t=us-central1-docker.pkg.dev/atgeir-moae-dev/hr-portal-repo/frontend:1.0.0'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/atgeir-moae-dev/hr-portal-repo/frontend:1.0.0'
