"""
resume_downloader — FastAPI route, mirrors the old `hr-dev-resume-downloader`
Cloud Function (get_resume). Fetches a candidate's resume PDF from GCS,
runs an AI-generated-content forensic check on it, and streams the PDF back
with the score in a response header.
"""

import io
import json

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse, Response
from google.cloud import bigquery
import vertexai
from vertexai.generative_models import GenerativeModel
from pypdf import PdfReader

import config
from bigquery_client import bq_client
from gcs_client import gcs_client

router = APIRouter()

PROJECT_ID  = config.GCP_PROJECT_ID
DATASET_ID  = config.BQ_DATASET_ID
TABLE_ID    = "candidates"
BUCKET_NAME = config.GCS_BUCKET_NAME

# Initialize Vertex AI globally for warm container reuse
vertexai.init(project=PROJECT_ID, location=config.VERTEX_AI_LOCATION)
ai_model = GenerativeModel("gemini-3.5-flash")


def _error(message: str, status: int = 400):
    return JSONResponse({"success": False, "error": message}, status_code=status)


# ── Fetch gcs_pdf_path + job_id from BigQuery ────────────────────────────────

def fetch_candidate_info(candidate_id: str) -> dict | None:
    query = f"""
        SELECT gcs_pdf_path, job_id
        FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
        WHERE candidate_id = @candidate_id
        LIMIT 1
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("candidate_id", "STRING", candidate_id)
        ]
    )
    rows = list(bq_client.query(query, job_config=job_config).result())
    if not rows or not rows[0].gcs_pdf_path:
        return None
    return {
        "gcs_pdf_path": rows[0].gcs_pdf_path,
        "job_id"      : rows[0].job_id if rows[0].job_id else None,
    }


# ── Resolve the correct blob name ────────────────────────────────────────────

def resolve_blob_name(gcs_pdf_path: str, job_id: str | None) -> str:
    path = gcs_pdf_path
    if path.startswith("gs://"):
        path = path[len("gs://"):]
        path = "/".join(path.split("/")[1:])

    filename = path.split("/")[-1]

    if job_id:
        return f"resumes/{job_id}/{filename}"

    return path


# ── Download PDF bytes from GCS ───────────────────────────────────────────────

def download_pdf(blob_name: str) -> bytes:
    bucket = gcs_client.bucket(BUCKET_NAME)
    blob   = bucket.blob(blob_name)
    return blob.download_as_bytes()


# ── AI Forensic Analysis ──────────────────────────────────────────────────────

def assess_ai_percentage(pdf_bytes: bytes) -> str:
    """Extracts PDF text and asks Gemini Flash to assess LLM probability."""
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        text = "\n".join([page.extract_text() for page in reader.pages if page.extract_text()])

        if not text.strip():
            return "0"

        prompt = f"""
        You are an expert forensic copywriter. Analyze this resume text. 
        Calculate the percentage probability (0 to 100) that this text was generated by an AI. Look for telltale signs: extreme semantic symmetry, robotic transition words ('spearheaded', 'testament to', 'fostered'), zero personal idiosyncrasies, and hyper-dense buzzword packing.
        
        Return strictly a JSON object matching this schema: {{"ai_percentage": integer}}
        
        Resume Text:
        '''{text[:10000]}'''
        """

        response = ai_model.generate_content(
            prompt,
            generation_config={"response_mime_type": "application/json"}
        )

        result = json.loads(response.text)
        return str(result.get("ai_percentage", 0))

    except Exception as e:
        print(f"AI Assessment failed: {str(e)}")
        return "unknown"


# ── Entry point ───────────────────────────────────────────────────────────────

@router.get("/api/resume-downloader")
@router.post("/api/resume-downloader")
async def get_resume(request: Request):
    candidate_id = request.query_params.get("candidate_id", "").strip()

    if not candidate_id and request.method == "POST":
        try:
            body = await request.json()
            candidate_id = (body or {}).get("candidate_id", "").strip()
        except Exception:
            pass

    if not candidate_id:
        return _error("'candidate_id' is required", 400)

    try:
        info = fetch_candidate_info(candidate_id)
    except Exception as e:
        return _error(f"BigQuery error: {str(e)}", 500)

    if not info:
        return _error(f"No resume found for candidate_id: {candidate_id}", 404)

    blob_name = resolve_blob_name(info["gcs_pdf_path"], info.get("job_id"))
    filename  = blob_name.split("/")[-1] or "resume.pdf"

    try:
        pdf_bytes = download_pdf(blob_name)
    except Exception:
        return _error(f"Failed to fetch resume from GCS. Path: {blob_name!r}", 500)

    ai_score = assess_ai_percentage(pdf_bytes)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'inline; filename="{filename}"',
            "X-AI-Generated-Percentage": ai_score,
        },
    )